### PR TITLE
Remove the logger from the interface methods

### PR DESCRIPTION
**Pull request by Skarlso**
### Description

https://github.com/weaveworks/pctl/issues/166

### Checklist
- [x] Added tests that cover your change
- [x] Added/modified documentation as required (such as the `README.md` (diagrams, usage, roadmap etc), and anything in `examples/`)
- [x] Made sure the title of the PR is a good description that can go into the release notes
- [x] Added a `kind` label to the PR (e.g. `kind/feature`)

### CODE REVIEW

**Review by aclevername — CHANGES_REQUESTED** [review]
Its passed in rather than set on the catalog because the logger gets modified for each catalog source https://github.com/weaveworks/profiles/blob/ef740a45e3038e476de957fa2bc5b3be14c7676f/controllers/profilecatalogsource_controller.go#L63

**Comment by bigkevmcd** [comment]
> Its passed in rather than set on the catalog because the logger gets modified for each catalog source
> 
> https://github.com/weaveworks/profiles/blob/ef740a45e3038e476de957fa2bc5b3be14c7676f/controllers/profilecatalogsource_controller.go#L63

That's not quite what's happening there, when you call:

```go
logger := r.Log.WithValues("profilecatalogsource", req.NamespacedName) 
```

You get a clone of the original logger, but with additional log context values.

It's perfectly safe to do this.

**Comment by Skarlso** [comment]
> Its passed in rather than set on the catalog because the logger gets modified for each request
> 
> https://github.com/weaveworks/profiles/blob/ef740a45e3038e476de957fa2bc5b3be14c7676f/pkg/api/api.go#L94

I see, good point. But this can be shifted into the function itself. Which also makes more sense. The function itself can give more context.

**Comment by Skarlso** [comment]
> > Its passed in rather than set on the catalog because the logger gets modified for each request
> > https://github.com/weaveworks/profiles/blob/ef740a45e3038e476de957fa2bc5b3be14c7676f/pkg/api/api.go#L94
> 
> I see, good point. But this can be shifted into the function itself. Which also makes more sense. The function itself can give more context.

Also, to be fair, this whole thing changed in #184 a bit.

**Comment by aclevername** [comment]
> > Its passed in rather than set on the catalog because the logger gets modified for each catalog source
> > https://github.com/weaveworks/profiles/blob/ef740a45e3038e476de957fa2bc5b3be14c7676f/controllers/profilecatalogsource_controller.go#L63
> 
> That's not quite what's happening there, when you call:
> 
> ```go
> logger := r.Log.WithValues("profilecatalogsource", req.NamespacedName) 
> ```
> 
> You get a clone of the original logger, but with additional log context values.
> 
> It's perfectly safe to do this.
> 
> EDIT: https://github.com/go-logr/logr/blob/master/logr.go#L236

I updated my comment as the link was wrong. I'm not sure what your point your trying to convey :smile: ? I wasn't saying it was dangerous, just that its intentional that we pass the logger in. Its useful as it contains more context (more key:values) about the request. If we set the logger on the catalog struct and don't pass it in each time we don't gain this new context.

**Comment by aclevername** [comment]
> > Its passed in rather than set on the catalog because the logger gets modified for each request
> > https://github.com/weaveworks/profiles/blob/ef740a45e3038e476de957fa2bc5b3be14c7676f/pkg/api/api.go#L94
> 
> I see, good point. But this can be shifted into the function itself. Which also makes more sense. The function itself can give more context.

I am not an expert structured logger (or an expert at anything :laughing: ), but I think it makes more sense to set it at the request entry point? It sort of makes the whole flow quite clean as all the context is set at the very beginning. But Its not a hill I'm going to die on, so feel free to refactor :smile:

**Comment by Skarlso** [comment]
> > > Its passed in rather than set on the catalog because the logger gets modified for each request
> > > https://github.com/weaveworks/profiles/blob/ef740a45e3038e476de957fa2bc5b3be14c7676f/pkg/api/api.go#L94
> > 
> > 
> > I see, good point. But this can be shifted into the function itself. Which also makes more sense. The function itself can give more context.
> 
> I am not an expert structured logger (or an expert at anything 😆 ), but I think it makes more sense to set it at the request entry point? It sort of makes the whole flow quite clean as all the context is set at the very beginning. But Its not a hill I'm going to die on, so feel free to refactor 😄

I get your point, I do. But then the others should also have logging? :D Like, it's weird that only two out of the five have it. :D

**Comment by aclevername** [comment]
> > > > Its passed in rather than set on the catalog because the logger gets modified for each request
> > > > https://github.com/weaveworks/profiles/blob/ef740a45e3038e476de957fa2bc5b3be14c7676f/pkg/api/api.go#L94
> > > 
> > > 
> > > I see, good point. But this can be shifted into the function itself. Which also makes more sense. The function itself can give more context.
> > 
> > 
> > I am not an expert structured logger (or an expert at anything laughing ), but I think it makes more sense to set it at the request entry point? It sort of makes the whole flow quite clean as all the context is set at the very beginning. But Its not a hill I'm going to die on, so feel free to refactor smile
> 
> I get your point, I do. But then the others should also have logging? :D Like, it's weird that only two out of the five have it. :D

I think thats purely because they don't have anything "worth" logging. Only the version comparisions have errors that can occur, hence the logger being passed in :smile:

**Comment by Skarlso** [comment]
> > > > > Its passed in rather than set on the catalog because the logger gets modified for each request
> > > > > https://github.com/weaveworks/profiles/blob/ef740a45e3038e476de957fa2bc5b3be14c7676f/pkg/api/api.go#L94
> > > > 
> > > > 
> > > > I see, good point. But this can be shifted into the function itself. Which also makes more sense. The function itself can give more context.
> > > 
> > > 
> > > I am not an expert structured logger (or an expert at anything laughing ), but I think it makes more sense to set it at the request entry point? It sort of makes the whole flow quite clean as all the context is set at the very beginning. But Its not a hill I'm going to die on, so feel free to refactor smile
> > 
> > 
> > I get your point, I do. But then the others should also have logging? :D Like, it's weird that only two out of the five have it. :D
> 
> I think thats purely because they don't have anything "worth" logging. Only the version comparisions have errors that can occur, hence the logger being passed in 😄

Fiinnnneee. But I'm fixing the frigging pr label checker :D

**Pull request closed without merging**
