### PR TITLE
Render schema component in docs

### PR DESCRIPTION
**Pull request by Himangini**
### Description
I have added the functionality to render the schema component with a JSON file with docusaurus markdown.

_NOTE_ The json files `catalogdef.json` and `profiledef.json` used here are autogenerated. Related PR https://github.com/weaveworks/profiles/pull/254/ that automates schema generation

The component picks up the schema from the specified JSON file and renders it into an HTML table.
Added some minor styling as well. The build of the docs using `yarn build` doesn't error for the component and it generates both client and serverside files. The `Schema.js` file [taken from eksctl project] is adapted to work with docusaurus rendering, it may not work the same way with other docs frameworks.

Screenshot 2021-08-10 at 09 43 16

Part of #239 

### Checklist
- [ ] Added tests that cover your change
- [ ] Added/modified documentation as required (such as the `README.md` (diagrams, usage, roadmap etc), and anything in `examples/`)
- [x] Made sure the title of the PR is a good description that can go into the release notes
- [x] Added a `kind` label to the PR (e.g. `kind/feature`)

### CODE REVIEW

**Comment by Callisto13** [comment]
😕  I feel kinda bad that we got Alina working on this for days

**Comment by Himangini** [comment]
> 😕 I feel kinda bad that we got Alina working on this for days. Plus we already had a PR open 🤷‍♀️

I checked your branch, the component doesn't render. This has been dragging on quite a while now. Also, your PR is doing too many things in the same branch, I just moved the react component part in this PR so it's easier to review/test/merge

**Comment by Callisto13** [comment]
> the component doesn't render

Yes, this is why Alina and I have been working on it. We will be updating that branch today.

> your PR is doing too many things in the same branch, I just moved the react component part in this PR so it's easier to review/test/merge

That is valid, Alina can open a new branch with the rendering side.

**Comment by Himangini** [comment]
Thanks, @Callisto13  for letting me know Alina has an amazing solution for this, so I am closing my PR :)

**Pull request closed without merging**
