### PR TITLE
Match version field to regex

### PR DESCRIPTION
**Pull request by aclevername**
### Description

regexr.com/5tu4v regex playground with tests

### Checklist
- [ ] Added tests that cover your change
- [ ] Added/modified documentation as required (such as the `README.md` (diagrams, usage, roadmap etc), and anything in `examples/`)
- [ ] Made sure the title of the PR is a good description that can go into the release notes
- [ ] Added a `kind` label to the PR (e.g. `kind/feature`)

### CODE REVIEW

**Review by Skarlso — APPROVED** [review]
LGTM,
We can release this together with my other PR

**Comment by bigkevmcd** [comment]
Shouldn't there be a test for this?

**Comment by Skarlso** [comment]
Also, can you add tests please? :))

**Comment by Skarlso** [comment]
Although you do say `regexr.com/5tu4v regex playground with tests` also, you did not tick the tests yet, so I assume you are working on it. :DDDD

**Comment by aclevername** [comment]
added test

**Comment by Callisto13** [comment]
so glad to see aunt ethel is still crushing it

**Review by Skarlso — APPROVED** [review]

**Pull request merged**
